# Funding options for Gira++
# This file is optional but helps with project visibility on GitHub

# You can add funding platforms here if you want to accept donations
# github: [seiflesbat]
# patreon: your_username
# ko_fi: your_username

# For now, we keep it open-source and free without requiring donations
